#heading(numbering: none)[Bảng ký hiệu]

#block[
  #table(
    columns: (auto, 1fr),
    align: (left + horizon, left + horizon),
    inset: (left: 1em, right: 1em),
    [API], [Application Programming Interface - Giao diện lập trình ứng dụng],
    [ASan], [AddressSanitizer - Công cụ phát hiện lỗi truy cập bộ nhớ],
    [COW], [Copy-on-Write - Sao chép khi ghi],
    [CPU], [Central Processing Unit - Bộ xử lý trung tâm],
    [CSV], [Comma-Separated Values - Định dạng dữ liệu phân tách bằng dấu phẩy],
    [DPR], [Device Pixel Ratio - Tỉ lệ điểm ảnh thiết bị],
    [FIFO], [First In First Out - Vào trước ra trước (ống dẫn dữ liệu)],
    [FPS], [Frames Per Second - Số khung hình mỗi giây],
    [GLSL], [OpenGL Shading Language - Ngôn ngữ đổ bóng của OpenGL],
    [GPU], [Graphics Processing Unit - Bộ xử lý đồ họa],
    [GUI], [Graphical User Interface - Giao diện đồ họa người dùng],
    [HiDPI], [High Dots Per Inch - Màn hình mật độ điểm ảnh cao],
    [HMI], [Human-Machine Interface - Giao diện người-máy],
    [I/O], [Input/Output - Nhập/xuất dữ liệu],
    [JSON], [JavaScript Object Notation - Định dạng dữ liệu JSON],
    [LOD], [Level of Detail - Mức chi tiết],
    [LTTB], [Largest Triangle Three Buckets - Giảm mẫu theo tam giác lớn nhất ba xô],
    [MOC], [Meta-Object Compiler - Trình biên dịch Meta-Object],
    [MSAA], [Multi-Sample Anti-Aliasing - Khử răng cưa đa mẫu],
    [MVP], [Model-View-Projection - Ma trận mô hình-khung nhìn-phép chiếu],
    [NaN], [Not a Number - Giá trị số không hợp lệ],
    [OpenGL], [Open Graphics Library - Thư viện đồ họa mở],
    [QML], [Qt Modeling Language - Ngôn ngữ mô tả giao diện của Qt],
    [RFC], [Request for Comments - Tài liệu chuẩn kỹ thuật của IETF],
    [RGBA], [Red Green Blue Alpha - Kênh màu đỏ-lục-lam kèm độ trong suốt],
    [RHI], [Rendering Hardware Interface - Lớp trừu tượng đồ họa của Qt],
    [RSS], [Resident Set Size - Bộ nhớ thường trú của tiến trình],
    [SDF], [Signed Distance Field - Trường khoảng cách có dấu],
    [UI], [User Interface - Giao diện người dùng],
    [UML], [Unified Modeling Language - Ngôn ngữ mô hình hóa thống nhất],
    [UTC], [Coordinated Universal Time - Giờ phối hợp quốc tế],
    [VAO], [Vertex Array Object - Đối tượng mảng đỉnh],
    [VBO], [Vertex Buffer Object - Đối tượng bộ đệm đỉnh],
  )
]
